---
node:
  kubernetes:
    confs:
      - "/var/lib/kubelet/kubeconfig"
    kubeconfig:
      - "/var/lib/kubelet/kubeconfig"

  kubelet:
    defaultconf: "/home/kubernetes/kubelet-config.yaml"
    defaultsvc: "/etc/systemd/system/kubelet.service"
    defaultkubeconfig: "/var/lib/kubelet/kubeconfig"

  proxy:
    defaultkubeconfig: "/var/lib/kubelet/kubeconfig"
